// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lckynuqsjvcocrzwcdte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxja3ludXFzanZjb2NyendjZHRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzY3NjksImV4cCI6MjA2OTk1Mjc2OX0.GVn7Eqt9CR_sG1DB0CnGfm_RfsOtMhdtn285PjmIyjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});